import { basicScenarios } from './basic';
import { parentScenarios } from './parents';
import { specialCaseScenarios } from './special-cases';
import { extendedBasicScenarios } from './extended-basic';
import { blockingScenarios } from './blocking-cases';
import { extendedAwlScenarios } from './extended-awl';
import { extendedRaddScenarios } from './extended-radd';
import { distantKindredScenarios } from './distant-kindred-scenarios';
import { moreScenarios } from './more-scenarios';
import { grandfatherScenarios } from './grandfather-scenarios';
import { autoGeneratedScenarios } from './auto-generated';
import { WorkedExample } from '../../../models';

export const workedExamples: WorkedExample[] = [
  ...basicScenarios,
  ...parentScenarios,
  ...specialCaseScenarios,
  ...extendedBasicScenarios,
  ...blockingScenarios,
  ...extendedAwlScenarios,
  ...extendedRaddScenarios,
  ...distantKindredScenarios,
  ...moreScenarios,
  ...grandfatherScenarios,
  ...autoGeneratedScenarios
];
